spring.application.name=vetcare-api

spring.datasource.url=jdbc:postgresql://localhost:5432/vetcare
spring.datasource.username=postgres
spring.datasource.password=Db2806@!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true